/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author sisir
 */
public class MenuParametros extends javax.swing.JFrame {

    /**
     * Creates new form MenuHP
     */
    public MenuParametros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        guardarconfg = new javax.swing.JButton();
        volverMenu = new javax.swing.JButton();
        panelDias = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        decreaseDay = new javax.swing.JButton();
        increaseDay = new javax.swing.JButton();
        dayDurationValue = new javax.swing.JTextField();
        decreaseDeadline = new javax.swing.JButton();
        increaseDeadline = new javax.swing.JButton();
        deadlineValue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panelHP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        menosPB1 = new javax.swing.JButton();
        masPB1 = new javax.swing.JButton();
        valorPB1 = new javax.swing.JTextField();
        menosCPU1 = new javax.swing.JButton();
        masCPU1 = new javax.swing.JButton();
        valorCPU1 = new javax.swing.JTextField();
        menosRAM1 = new javax.swing.JButton();
        masRAM1 = new javax.swing.JButton();
        valorRAM1 = new javax.swing.JTextField();
        menosFA1 = new javax.swing.JButton();
        masFA1 = new javax.swing.JButton();
        valorFA1 = new javax.swing.JTextField();
        menosTG1 = new javax.swing.JButton();
        masTG1 = new javax.swing.JButton();
        valorTG1 = new javax.swing.JTextField();
        menosEns1 = new javax.swing.JButton();
        masEns1 = new javax.swing.JButton();
        valorEns1 = new javax.swing.JTextField();
        maximoTrabajador1 = new javax.swing.JTextField();
        panelDell = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        menosPB = new javax.swing.JButton();
        masPB = new javax.swing.JButton();
        valorPB = new javax.swing.JTextField();
        menosCPU = new javax.swing.JButton();
        masCPU = new javax.swing.JButton();
        valorCPU = new javax.swing.JTextField();
        menosRAM = new javax.swing.JButton();
        masRAM = new javax.swing.JButton();
        valorRAM = new javax.swing.JTextField();
        menosFA = new javax.swing.JButton();
        masFA = new javax.swing.JButton();
        valorFA = new javax.swing.JTextField();
        menosTG = new javax.swing.JButton();
        masTG = new javax.swing.JButton();
        valorTG = new javax.swing.JTextField();
        menosEns = new javax.swing.JButton();
        masEns = new javax.swing.JButton();
        valorEns = new javax.swing.JTextField();
        maximoTrabajador = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/logo-HP_1.png"))); // NOI18N
        jPanel1.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 200, 140));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/logo_Dell_1.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 210, 90));

        Titulo.setFont(new java.awt.Font("Stencil", 0, 65)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("CONFIGURACION");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 570, 70));

        guardarconfg.setBackground(new java.awt.Color(0, 0, 255));
        guardarconfg.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        guardarconfg.setForeground(new java.awt.Color(255, 255, 255));
        guardarconfg.setText("Guardar");
        guardarconfg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarconfgActionPerformed(evt);
            }
        });
        jPanel1.add(guardarconfg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 180, 50));

        volverMenu.setBackground(new java.awt.Color(0, 0, 255));
        volverMenu.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        volverMenu.setForeground(new java.awt.Color(255, 255, 255));
        volverMenu.setText("Volver");
        volverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(volverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 180, 50));

        panelDias.setBackground(new java.awt.Color(0, 51, 51));
        panelDias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDias.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Duracion");

        jLabel28.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Duracion de los dias:");

        jLabel29.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Dias entre entregas");

        decreaseDay.setBackground(new java.awt.Color(51, 51, 51));
        decreaseDay.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        decreaseDay.setForeground(new java.awt.Color(255, 255, 255));
        decreaseDay.setText("-");
        decreaseDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decreaseDayMouseClicked(evt);
            }
        });
        decreaseDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseDayActionPerformed(evt);
            }
        });

        increaseDay.setBackground(new java.awt.Color(51, 51, 51));
        increaseDay.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        increaseDay.setForeground(new java.awt.Color(255, 255, 255));
        increaseDay.setText("+");
        increaseDay.setBorderPainted(false);
        increaseDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                increaseDayMouseClicked(evt);
            }
        });
        increaseDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseDayActionPerformed(evt);
            }
        });

        dayDurationValue.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        dayDurationValue.setForeground(new java.awt.Color(51, 51, 51));
        dayDurationValue.setText("0");
        dayDurationValue.setBorder(null);
        dayDurationValue.setFocusable(false);
        dayDurationValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayDurationValueActionPerformed(evt);
            }
        });

        decreaseDeadline.setBackground(new java.awt.Color(51, 51, 51));
        decreaseDeadline.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        decreaseDeadline.setForeground(new java.awt.Color(255, 255, 255));
        decreaseDeadline.setText("-");
        decreaseDeadline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decreaseDeadlineMouseClicked(evt);
            }
        });
        decreaseDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseDeadlineActionPerformed(evt);
            }
        });

        increaseDeadline.setBackground(new java.awt.Color(51, 51, 51));
        increaseDeadline.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        increaseDeadline.setForeground(new java.awt.Color(255, 255, 255));
        increaseDeadline.setText("+");
        increaseDeadline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                increaseDeadlineMouseClicked(evt);
            }
        });
        increaseDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseDeadlineActionPerformed(evt);
            }
        });

        deadlineValue.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        deadlineValue.setForeground(new java.awt.Color(51, 51, 51));
        deadlineValue.setText("0");
        deadlineValue.setBorder(null);
        deadlineValue.setFocusable(false);
        deadlineValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadlineValueActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("(segundos)");

        javax.swing.GroupLayout panelDiasLayout = new javax.swing.GroupLayout(panelDias);
        panelDias.setLayout(panelDiasLayout);
        panelDiasLayout.setHorizontalGroup(
            panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDiasLayout.createSequentialGroup()
                        .addGroup(panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDiasLayout.createSequentialGroup()
                                .addComponent(decreaseDay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayDurationValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(increaseDay))
                            .addGroup(panelDiasLayout.createSequentialGroup()
                                .addComponent(decreaseDeadline)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deadlineValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(increaseDeadline)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDiasLayout.setVerticalGroup(
            panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decreaseDay)
                    .addComponent(increaseDay)
                    .addComponent(dayDurationValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decreaseDeadline)
                    .addComponent(increaseDeadline)
                    .addComponent(deadlineValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(panelDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 270, 210));

        panelHP.setBackground(new java.awt.Color(0, 0, 51));
        panelHP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHP.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PARAMETROS hp");

        jLabel14.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Productores PB");

        jLabel18.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Productores de CPUs");

        jLabel21.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Productores de RAM");

        jLabel22.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Productores de Fuente");

        jLabel23.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("de Alimentación");

        jLabel24.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Gráfica");

        jLabel25.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Productores de Tarjeta");

        jLabel26.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Ensambladores");

        jLabel27.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("MÁXIMO");

        menosPB1.setBackground(new java.awt.Color(51, 51, 51));
        menosPB1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosPB1.setForeground(new java.awt.Color(255, 255, 255));
        menosPB1.setText("-");
        menosPB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosPB1MouseClicked(evt);
            }
        });
        menosPB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosPB1ActionPerformed(evt);
            }
        });

        masPB1.setBackground(new java.awt.Color(51, 51, 51));
        masPB1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masPB1.setForeground(new java.awt.Color(255, 255, 255));
        masPB1.setText("+");
        masPB1.setBorderPainted(false);
        masPB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masPB1MouseClicked(evt);
            }
        });
        masPB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masPB1ActionPerformed(evt);
            }
        });

        valorPB1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorPB1.setForeground(new java.awt.Color(51, 51, 51));
        valorPB1.setText("0");
        valorPB1.setBorder(null);
        valorPB1.setFocusable(false);
        valorPB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPB1ActionPerformed(evt);
            }
        });

        menosCPU1.setBackground(new java.awt.Color(51, 51, 51));
        menosCPU1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosCPU1.setForeground(new java.awt.Color(255, 255, 255));
        menosCPU1.setText("-");
        menosCPU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosCPU1MouseClicked(evt);
            }
        });
        menosCPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosCPU1ActionPerformed(evt);
            }
        });

        masCPU1.setBackground(new java.awt.Color(51, 51, 51));
        masCPU1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masCPU1.setForeground(new java.awt.Color(255, 255, 255));
        masCPU1.setText("+");
        masCPU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masCPU1MouseClicked(evt);
            }
        });
        masCPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masCPU1ActionPerformed(evt);
            }
        });

        valorCPU1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorCPU1.setForeground(new java.awt.Color(51, 51, 51));
        valorCPU1.setText("0");
        valorCPU1.setBorder(null);
        valorCPU1.setFocusable(false);
        valorCPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorCPU1ActionPerformed(evt);
            }
        });

        menosRAM1.setBackground(new java.awt.Color(51, 51, 51));
        menosRAM1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosRAM1.setForeground(new java.awt.Color(255, 255, 255));
        menosRAM1.setText("-");
        menosRAM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosRAM1MouseClicked(evt);
            }
        });
        menosRAM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosRAM1ActionPerformed(evt);
            }
        });

        masRAM1.setBackground(new java.awt.Color(51, 51, 51));
        masRAM1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masRAM1.setForeground(new java.awt.Color(255, 255, 255));
        masRAM1.setText("+");
        masRAM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masRAM1MouseClicked(evt);
            }
        });
        masRAM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masRAM1ActionPerformed(evt);
            }
        });

        valorRAM1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorRAM1.setForeground(new java.awt.Color(51, 51, 51));
        valorRAM1.setText("0");
        valorRAM1.setBorder(null);
        valorRAM1.setFocusable(false);
        valorRAM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorRAM1ActionPerformed(evt);
            }
        });

        menosFA1.setBackground(new java.awt.Color(51, 51, 51));
        menosFA1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosFA1.setForeground(new java.awt.Color(255, 255, 255));
        menosFA1.setText("-");
        menosFA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosFA1MouseClicked(evt);
            }
        });
        menosFA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosFA1ActionPerformed(evt);
            }
        });

        masFA1.setBackground(new java.awt.Color(51, 51, 51));
        masFA1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masFA1.setForeground(new java.awt.Color(255, 255, 255));
        masFA1.setText("+");
        masFA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masFA1MouseClicked(evt);
            }
        });
        masFA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masFA1ActionPerformed(evt);
            }
        });

        valorFA1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorFA1.setForeground(new java.awt.Color(51, 51, 51));
        valorFA1.setText("0");
        valorFA1.setBorder(null);
        valorFA1.setFocusable(false);
        valorFA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFA1ActionPerformed(evt);
            }
        });

        menosTG1.setBackground(new java.awt.Color(51, 51, 51));
        menosTG1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosTG1.setForeground(new java.awt.Color(255, 255, 255));
        menosTG1.setText("-");
        menosTG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosTG1MouseClicked(evt);
            }
        });
        menosTG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosTG1ActionPerformed(evt);
            }
        });

        masTG1.setBackground(new java.awt.Color(51, 51, 51));
        masTG1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masTG1.setForeground(new java.awt.Color(255, 255, 255));
        masTG1.setText("+");
        masTG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masTG1MouseClicked(evt);
            }
        });
        masTG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masTG1ActionPerformed(evt);
            }
        });

        valorTG1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorTG1.setForeground(new java.awt.Color(51, 51, 51));
        valorTG1.setText("0");
        valorTG1.setBorder(null);
        valorTG1.setFocusable(false);
        valorTG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTG1ActionPerformed(evt);
            }
        });

        menosEns1.setBackground(new java.awt.Color(51, 51, 51));
        menosEns1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosEns1.setForeground(new java.awt.Color(255, 255, 255));
        menosEns1.setText("-");
        menosEns1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosEns1MouseClicked(evt);
            }
        });
        menosEns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosEns1ActionPerformed(evt);
            }
        });

        masEns1.setBackground(new java.awt.Color(51, 51, 51));
        masEns1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masEns1.setForeground(new java.awt.Color(255, 255, 255));
        masEns1.setText("+");
        masEns1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masEns1MouseClicked(evt);
            }
        });
        masEns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masEns1ActionPerformed(evt);
            }
        });

        valorEns1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorEns1.setForeground(new java.awt.Color(51, 51, 51));
        valorEns1.setText("0");
        valorEns1.setBorder(null);
        valorEns1.setFocusable(false);
        valorEns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorEns1ActionPerformed(evt);
            }
        });

        maximoTrabajador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maximoTrabajador1.setText("14");
        maximoTrabajador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximoTrabajador1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHPLayout = new javax.swing.GroupLayout(panelHP);
        panelHP.setLayout(panelHPLayout);
        panelHPLayout.setHorizontalGroup(
            panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHPLayout.createSequentialGroup()
                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelHPLayout.createSequentialGroup()
                        .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHPLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHPLayout.createSequentialGroup()
                                        .addComponent(menosPB1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorPB1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masPB1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelHPLayout.createSequentialGroup()
                                            .addComponent(menosFA1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(valorFA1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(masFA1))
                                        .addGroup(panelHPLayout.createSequentialGroup()
                                            .addComponent(menosCPU1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(valorCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(masCPU1))
                                        .addGroup(panelHPLayout.createSequentialGroup()
                                            .addComponent(menosRAM1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(valorRAM1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(masRAM1))
                                        .addGroup(panelHPLayout.createSequentialGroup()
                                            .addComponent(menosTG1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(valorTG1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(masTG1)))))
                            .addGroup(panelHPLayout.createSequentialGroup()
                                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelHPLayout.createSequentialGroup()
                                        .addComponent(menosEns1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorEns1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masEns1))
                                    .addComponent(maximoTrabajador1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        panelHPLayout.setVerticalGroup(
            panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menosPB1)
                    .addComponent(masPB1)
                    .addComponent(valorPB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menosCPU1)
                    .addComponent(masCPU1)
                    .addComponent(valorCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masRAM1)
                    .addComponent(menosRAM1)
                    .addComponent(valorRAM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHPLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masFA1)
                        .addComponent(menosFA1)
                        .addComponent(valorFA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHPLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masTG1)
                        .addComponent(menosTG1)
                        .addComponent(valorTG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masEns1)
                    .addComponent(menosEns1)
                    .addComponent(valorEns1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maximoTrabajador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        panelDell.setBackground(new java.awt.Color(0, 0, 51));
        panelDell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDell.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PARAMETROS dELL");

        jLabel10.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Productores PB");

        jLabel11.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Productores de CPUs");

        jLabel12.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Productores de RAM");

        jLabel13.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Productores de Fuente");

        jLabel16.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("de Alimentación");

        jLabel17.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Gráfica");

        jLabel15.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Productores de Tarjeta");

        jLabel19.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Ensambladores");

        jLabel20.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("MÁXIMO");

        menosPB.setBackground(new java.awt.Color(51, 51, 51));
        menosPB.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosPB.setForeground(new java.awt.Color(255, 255, 255));
        menosPB.setText("-");
        menosPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosPBMouseClicked(evt);
            }
        });
        menosPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosPBActionPerformed(evt);
            }
        });

        masPB.setBackground(new java.awt.Color(51, 51, 51));
        masPB.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masPB.setForeground(new java.awt.Color(255, 255, 255));
        masPB.setText("+");
        masPB.setBorderPainted(false);
        masPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masPBMouseClicked(evt);
            }
        });
        masPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masPBActionPerformed(evt);
            }
        });

        valorPB.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorPB.setForeground(new java.awt.Color(51, 51, 51));
        valorPB.setText("0");
        valorPB.setBorder(null);
        valorPB.setFocusable(false);
        valorPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPBActionPerformed(evt);
            }
        });

        menosCPU.setBackground(new java.awt.Color(51, 51, 51));
        menosCPU.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosCPU.setForeground(new java.awt.Color(255, 255, 255));
        menosCPU.setText("-");
        menosCPU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosCPUMouseClicked(evt);
            }
        });
        menosCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosCPUActionPerformed(evt);
            }
        });

        masCPU.setBackground(new java.awt.Color(51, 51, 51));
        masCPU.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masCPU.setForeground(new java.awt.Color(255, 255, 255));
        masCPU.setText("+");
        masCPU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masCPUMouseClicked(evt);
            }
        });
        masCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masCPUActionPerformed(evt);
            }
        });

        valorCPU.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorCPU.setForeground(new java.awt.Color(51, 51, 51));
        valorCPU.setText("0");
        valorCPU.setBorder(null);
        valorCPU.setFocusable(false);
        valorCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorCPUActionPerformed(evt);
            }
        });

        menosRAM.setBackground(new java.awt.Color(51, 51, 51));
        menosRAM.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosRAM.setForeground(new java.awt.Color(255, 255, 255));
        menosRAM.setText("-");
        menosRAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosRAMMouseClicked(evt);
            }
        });
        menosRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosRAMActionPerformed(evt);
            }
        });

        masRAM.setBackground(new java.awt.Color(51, 51, 51));
        masRAM.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masRAM.setForeground(new java.awt.Color(255, 255, 255));
        masRAM.setText("+");
        masRAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masRAMMouseClicked(evt);
            }
        });
        masRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masRAMActionPerformed(evt);
            }
        });

        valorRAM.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorRAM.setForeground(new java.awt.Color(51, 51, 51));
        valorRAM.setText("0");
        valorRAM.setBorder(null);
        valorRAM.setFocusable(false);
        valorRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorRAMActionPerformed(evt);
            }
        });

        menosFA.setBackground(new java.awt.Color(51, 51, 51));
        menosFA.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosFA.setForeground(new java.awt.Color(255, 255, 255));
        menosFA.setText("-");
        menosFA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosFAMouseClicked(evt);
            }
        });
        menosFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosFAActionPerformed(evt);
            }
        });

        masFA.setBackground(new java.awt.Color(51, 51, 51));
        masFA.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masFA.setForeground(new java.awt.Color(255, 255, 255));
        masFA.setText("+");
        masFA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masFAMouseClicked(evt);
            }
        });
        masFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masFAActionPerformed(evt);
            }
        });

        valorFA.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorFA.setForeground(new java.awt.Color(51, 51, 51));
        valorFA.setText("0");
        valorFA.setBorder(null);
        valorFA.setFocusable(false);
        valorFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFAActionPerformed(evt);
            }
        });

        menosTG.setBackground(new java.awt.Color(51, 51, 51));
        menosTG.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosTG.setForeground(new java.awt.Color(255, 255, 255));
        menosTG.setText("-");
        menosTG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosTGMouseClicked(evt);
            }
        });
        menosTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosTGActionPerformed(evt);
            }
        });

        masTG.setBackground(new java.awt.Color(51, 51, 51));
        masTG.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masTG.setForeground(new java.awt.Color(255, 255, 255));
        masTG.setText("+");
        masTG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masTGMouseClicked(evt);
            }
        });
        masTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masTGActionPerformed(evt);
            }
        });

        valorTG.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorTG.setForeground(new java.awt.Color(51, 51, 51));
        valorTG.setText("0");
        valorTG.setBorder(null);
        valorTG.setFocusable(false);
        valorTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTGActionPerformed(evt);
            }
        });

        menosEns.setBackground(new java.awt.Color(51, 51, 51));
        menosEns.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        menosEns.setForeground(new java.awt.Color(255, 255, 255));
        menosEns.setText("-");
        menosEns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosEnsMouseClicked(evt);
            }
        });
        menosEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosEnsActionPerformed(evt);
            }
        });

        masEns.setBackground(new java.awt.Color(51, 51, 51));
        masEns.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        masEns.setForeground(new java.awt.Color(255, 255, 255));
        masEns.setText("+");
        masEns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masEnsMouseClicked(evt);
            }
        });
        masEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masEnsActionPerformed(evt);
            }
        });

        valorEns.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        valorEns.setForeground(new java.awt.Color(51, 51, 51));
        valorEns.setText("0");
        valorEns.setBorder(null);
        valorEns.setFocusable(false);
        valorEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorEnsActionPerformed(evt);
            }
        });

        maximoTrabajador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maximoTrabajador.setText("13");
        maximoTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximoTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDellLayout = new javax.swing.GroupLayout(panelDell);
        panelDell.setLayout(panelDellLayout);
        panelDellLayout.setHorizontalGroup(
            panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDellLayout.createSequentialGroup()
                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDellLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDellLayout.createSequentialGroup()
                        .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDellLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDellLayout.createSequentialGroup()
                                        .addComponent(menosPB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorPB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masPB))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelDellLayout.createSequentialGroup()
                                            .addComponent(menosFA)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(valorFA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(masFA))
                                        .addGroup(panelDellLayout.createSequentialGroup()
                                            .addComponent(menosCPU)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(valorCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(masCPU))
                                        .addGroup(panelDellLayout.createSequentialGroup()
                                            .addComponent(menosRAM)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(valorRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(masRAM))
                                        .addGroup(panelDellLayout.createSequentialGroup()
                                            .addComponent(menosTG)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(valorTG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(masTG)))))
                            .addGroup(panelDellLayout.createSequentialGroup()
                                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDellLayout.createSequentialGroup()
                                        .addComponent(menosEns)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorEns, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masEns))
                                    .addComponent(maximoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        panelDellLayout.setVerticalGroup(
            panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menosPB)
                    .addComponent(masPB)
                    .addComponent(valorPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menosCPU)
                    .addComponent(masCPU)
                    .addComponent(valorCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masRAM)
                    .addComponent(menosRAM)
                    .addComponent(valorRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDellLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masFA)
                        .addComponent(menosFA)
                        .addComponent(valorFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDellLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masTG)
                        .addComponent(menosTG)
                        .addComponent(valorTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masEns)
                    .addComponent(menosEns)
                    .addComponent(valorEns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maximoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 300, 450));

        Fondo.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/fondoPantalla.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masPBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masPBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masPBMouseClicked

    private void masPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masPBActionPerformed

    private void valorPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPBActionPerformed

    private void menosPBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosPBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosPBMouseClicked

    private void menosPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosPBActionPerformed

    private void valorCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorCPUActionPerformed

    private void masCPUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masCPUMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masCPUMouseClicked

    private void masCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masCPUActionPerformed

    private void menosCPUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosCPUMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosCPUMouseClicked

    private void menosCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosCPUActionPerformed

    private void valorRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorRAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorRAMActionPerformed

    private void menosRAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosRAMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosRAMMouseClicked

    private void menosRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosRAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosRAMActionPerformed

    private void masRAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masRAMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masRAMMouseClicked

    private void masRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masRAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masRAMActionPerformed

    private void menosFAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosFAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosFAMouseClicked

    private void menosFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosFAActionPerformed

    private void valorFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFAActionPerformed

    private void masFAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masFAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masFAMouseClicked

    private void masFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masFAActionPerformed

    private void menosTGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosTGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosTGMouseClicked

    private void menosTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosTGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosTGActionPerformed

    private void valorTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTGActionPerformed

    private void masTGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masTGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masTGMouseClicked

    private void masTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masTGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masTGActionPerformed

    private void menosEnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEnsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosEnsMouseClicked

    private void menosEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosEnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosEnsActionPerformed

    private void valorEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorEnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorEnsActionPerformed

    private void masEnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEnsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masEnsMouseClicked

    private void masEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masEnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masEnsActionPerformed

    private void maximoTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximoTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maximoTrabajadorActionPerformed

    private void menosPB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosPB1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosPB1MouseClicked

    private void menosPB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosPB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosPB1ActionPerformed

    private void masPB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masPB1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masPB1MouseClicked

    private void masPB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masPB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masPB1ActionPerformed

    private void valorPB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPB1ActionPerformed

    private void menosCPU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosCPU1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosCPU1MouseClicked

    private void menosCPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosCPU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosCPU1ActionPerformed

    private void masCPU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masCPU1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masCPU1MouseClicked

    private void masCPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masCPU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masCPU1ActionPerformed

    private void valorCPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorCPU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorCPU1ActionPerformed

    private void menosRAM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosRAM1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosRAM1MouseClicked

    private void menosRAM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosRAM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosRAM1ActionPerformed

    private void masRAM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masRAM1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masRAM1MouseClicked

    private void masRAM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masRAM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masRAM1ActionPerformed

    private void valorRAM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorRAM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorRAM1ActionPerformed

    private void menosFA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosFA1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosFA1MouseClicked

    private void menosFA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosFA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosFA1ActionPerformed

    private void masFA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masFA1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masFA1MouseClicked

    private void masFA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masFA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masFA1ActionPerformed

    private void valorFA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFA1ActionPerformed

    private void menosTG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosTG1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosTG1MouseClicked

    private void menosTG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosTG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosTG1ActionPerformed

    private void masTG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masTG1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masTG1MouseClicked

    private void masTG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masTG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masTG1ActionPerformed

    private void valorTG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTG1ActionPerformed

    private void menosEns1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEns1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menosEns1MouseClicked

    private void menosEns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosEns1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosEns1ActionPerformed

    private void masEns1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEns1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masEns1MouseClicked

    private void masEns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masEns1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masEns1ActionPerformed

    private void valorEns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorEns1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorEns1ActionPerformed

    private void maximoTrabajador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximoTrabajador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maximoTrabajador1ActionPerformed

    private void volverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverMenuActionPerformed

    private void guardarconfgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarconfgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarconfgActionPerformed

    private void decreaseDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decreaseDayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseDayMouseClicked

    private void decreaseDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseDayActionPerformed

    private void increaseDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increaseDayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseDayMouseClicked

    private void increaseDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseDayActionPerformed

    private void dayDurationValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayDurationValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayDurationValueActionPerformed

    private void decreaseDeadlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decreaseDeadlineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseDeadlineMouseClicked

    private void decreaseDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseDeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseDeadlineActionPerformed

    private void increaseDeadlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increaseDeadlineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseDeadlineMouseClicked

    private void increaseDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseDeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseDeadlineActionPerformed

    private void deadlineValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadlineValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deadlineValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuParametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField dayDurationValue;
    private javax.swing.JTextField deadlineValue;
    private javax.swing.JButton decreaseDay;
    private javax.swing.JButton decreaseDeadline;
    private javax.swing.JButton guardarconfg;
    private javax.swing.JButton increaseDay;
    private javax.swing.JButton increaseDeadline;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton masCPU;
    private javax.swing.JButton masCPU1;
    private javax.swing.JButton masEns;
    private javax.swing.JButton masEns1;
    private javax.swing.JButton masFA;
    private javax.swing.JButton masFA1;
    private javax.swing.JButton masPB;
    private javax.swing.JButton masPB1;
    private javax.swing.JButton masRAM;
    private javax.swing.JButton masRAM1;
    private javax.swing.JButton masTG;
    private javax.swing.JButton masTG1;
    private javax.swing.JTextField maximoTrabajador;
    private javax.swing.JTextField maximoTrabajador1;
    private javax.swing.JButton menosCPU;
    private javax.swing.JButton menosCPU1;
    private javax.swing.JButton menosEns;
    private javax.swing.JButton menosEns1;
    private javax.swing.JButton menosFA;
    private javax.swing.JButton menosFA1;
    private javax.swing.JButton menosPB;
    private javax.swing.JButton menosPB1;
    private javax.swing.JButton menosRAM;
    private javax.swing.JButton menosRAM1;
    private javax.swing.JButton menosTG;
    private javax.swing.JButton menosTG1;
    private javax.swing.JPanel panelDell;
    private javax.swing.JPanel panelDias;
    private javax.swing.JPanel panelHP;
    private javax.swing.JTextField valorCPU;
    private javax.swing.JTextField valorCPU1;
    private javax.swing.JTextField valorEns;
    private javax.swing.JTextField valorEns1;
    private javax.swing.JTextField valorFA;
    private javax.swing.JTextField valorFA1;
    private javax.swing.JTextField valorPB;
    private javax.swing.JTextField valorPB1;
    private javax.swing.JTextField valorRAM;
    private javax.swing.JTextField valorRAM1;
    private javax.swing.JTextField valorTG;
    private javax.swing.JTextField valorTG1;
    private javax.swing.JButton volverMenu;
    // End of variables declaration//GEN-END:variables
}
