/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Point;
import proyecto.operativosproyecto.App;


/**
 *
 * @author sisir
 */
public class MenuInicio extends javax.swing.JFrame {
    
    private Point initialClick;
    private final App app = App.getInstance();

    /**
     * Creates new form Menu
     */
    public MenuInicio() {
        initComponents();
        // Centra la ventana
        this.setLocationRelativeTo(null);
        // Evita que el usuario cambie el tamaño
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        simulacion = new javax.swing.JButton();
        companiaHP = new javax.swing.JButton();
        companiaDell = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        ParteInteractiva = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(0, 0, 153));
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, -1, -1));

        simulacion.setBackground(new java.awt.Color(0, 0, 102));
        simulacion.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        simulacion.setForeground(new java.awt.Color(255, 255, 255));
        simulacion.setText("SIMULACION");
        simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulacionActionPerformed(evt);
            }
        });
        jPanel1.add(simulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 260, 60));

        companiaHP.setBackground(new java.awt.Color(0, 0, 102));
        companiaHP.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        companiaHP.setForeground(new java.awt.Color(255, 255, 255));
        companiaHP.setText("HP");
        companiaHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companiaHPActionPerformed(evt);
            }
        });
        jPanel1.add(companiaHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 260, 60));

        companiaDell.setBackground(new java.awt.Color(0, 0, 102));
        companiaDell.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        companiaDell.setForeground(new java.awt.Color(255, 255, 255));
        companiaDell.setText("DELL");
        companiaDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companiaDellActionPerformed(evt);
            }
        });
        jPanel1.add(companiaDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 260, 60));

        modificar.setBackground(new java.awt.Color(0, 0, 102));
        modificar.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 260, 60));

        guardar.setBackground(new java.awt.Color(0, 0, 102));
        guardar.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 260, 60));

        Titulo.setFont(new java.awt.Font("Stencil", 0, 65)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("MENÚ DE INICIO");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 500, 90));

        ParteInteractiva.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("¡Bienvenido a la simulacion para comparar el rendimiento");

        jLabel7.setFont(new java.awt.Font("Cascadia Mono", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("de la compañía HP  con el de una compañía rival Dell!");

        javax.swing.GroupLayout ParteInteractivaLayout = new javax.swing.GroupLayout(ParteInteractiva);
        ParteInteractiva.setLayout(ParteInteractivaLayout);
        ParteInteractivaLayout.setHorizontalGroup(
            ParteInteractivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParteInteractivaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ParteInteractivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );
        ParteInteractivaLayout.setVerticalGroup(
            ParteInteractivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParteInteractivaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jPanel1.add(ParteInteractiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 580, 320));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/fondoPantalla.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -400, 1050, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        MenuParametros v3 = new MenuParametros();
        v3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarActionPerformed

    private void companiaHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companiaHPActionPerformed
        // TODO add your handling code here:
        MenuHP v2 = new MenuHP();
        v2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_companiaHPActionPerformed

    private void simulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simulacionActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void companiaDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companiaDellActionPerformed
        // TODO add your handling code here:
        MenuDell v1 = new MenuDell();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_companiaDellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ParteInteractiva;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton companiaDell;
    private javax.swing.JButton companiaHP;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton simulacion;
    // End of variables declaration//GEN-END:variables
}
